name: '✅🪲​​ Correções e Resolução de Bugs'
description: Reporte um problema técnico encontrado.
title: '[BUG]'
labels: ['bug']
assignees: []
body:
  - type: textarea
    id: descricao
    attributes:
      label: '📝 Descrição do problema'
      description: 'Descreva o problema em uma ou duas frases. O que precisa ser feito?'
      placeholder: 'Ex.: Botão criar projetos não funciona.'
    validations:
      required: true
  - type: textarea
    id: impacto
    attributes:
      label: '🚨​​ Qual o impacto no projeto?'
      description: 'O que o problema causa dentro do projeto?'
      placeholder: 'Ex.: O usuário fica impossibilitado de criar novos projetos.'
    validations:
      required: true
  - type: textarea
    id: reproducao
    attributes:
      label: '💽​ Como reproduzir?'
      description: 'Descreva como reproduzir.'
      placeholder: 'Ex.: '
    validations:
      required: false
  - type: textarea
    id: aceite
    attributes:
      label: '🕵️​ Critério de aceite'
      description: 'Descreva os critérios de aceite.'
      placeholder: 'Ex.: '
    validations:
      required: false
  - type: textarea
    id: contribuidores
    attributes:
      label: '🙌 Torne-se um colaborador'
      description: |
        Quando você enviar essa issue ou PR, peça para ser adicionado aos contribuidores usando o All Contributors Bot.
        Basta comentar nesta issue com o comando:
        ```
        @all-contributors please add @SEU_USUARIO for code, doc
        ```
        Substitua `@SEU_USUARIO` pelo seu usuário do GitHub e os tipos de contribuição (`code`, `doc`, etc.) de acordo com sua contribuição.
    validations:
      required: false