name: '🐞 Bug'
description: 'Reporte um problema técnico encontrado.'
title: '[BUG] '
labels: ['bug']
assignees: []
body:
  - type: textarea
    id: descricao
    attributes:
      label: '📝 Descrição do Problema'
    validations:
      required: true

  - type: textarea
    id: impacto
    attributes:
      label: '🚨 Impacto'
    validations:
      required: true

  - type: textarea
    id: reproducao
    attributes:
      label: '🔁 Passos para Reproduzir'
    validations:
      required: true

  - type: textarea
    id: esperado
    attributes:
      label: '✅ Comportamento Esperado'
    validations:
      required: true

  - type: checkboxes
    id: dod
    attributes:
      label: '📌 Definition of Done (DoD)'
      options:
        - label: Correção implementada
        - label: Testes atualizados/criados
        - label: Testes passando
        - label: PR revisado e aprovado